{{ if not .Values.tektonResources.enabled }}
{{- $envVar := . -}}
{{- range $clusterRoleBindingName, $clusterRoleBinding := .Values.clusterRoleBindings -}}
{{ include "sthings-helm-toolkit.cluster-role-binding" (list $envVar $clusterRoleBindingName $clusterRoleBinding) }}
{{ end -}}
{{ end -}}