{{ if not .Values.tektonResources.enabled }}
{{- $envVar := . -}}
{{- range $serviceAccountName, $serviceAccount := .Values.serviceAccounts -}}
{{ include "sthings-helm-toolkit.service-account" (list $envVar $serviceAccountName $serviceAccount) }}
{{ end -}}
{{ end -}}