---
version: 3
vars:
  # REGISTRY: eu.gcr.io
  # REPOSITORY_NAME: stuttgart-things
  REGISTRY: scr.cd43.sthings-pve.labul.sva.de
  REPOSITORY_NAME: machine-shop-operator
  MODULE: github.com/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}
  CONTAINER_RUNTIME_CMD: sudo nerdctl
  CONTROLLER_GEN_CMD: "./bin/controller-gen"
  KUSTOMIZE_CMD: /usr/bin/kustomize

  PROJECT_NAME:
    sh: pwd | grep -o "[^/]*$"
  VERSION:
    sh: git describe --tags --abbrev=0
  DATE:
    sh: date +"%y.%m%d.%H%M"
  UPDATED_TAG:
    sh: old_tag=$(git describe --tags --abbrev=0 | cut -d "." -f3 | cut -d "-" -f1); new_tag=$((old_tag+1)); echo $new_tag
  UPDATED_TAG_VERSION:
    sh: t1=$(git describe --tags --abbrev=0 | cut -f1 -d'.'); t2=$(git describe --tags --abbrev=0 | cut -f2 -d'.'); echo $t1.$t2.{{ .UPDATED_TAG }}
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD) ; fi
  TAG_VERSION:
    sh: "echo {{ .UPDATED_TAG_VERSION }} | sed 's/[^0-9^.]*//g'"

tasks:
  branch:
    desc: Create branch from main
    cmds:
      - git checkout main
      - git branch
      - git pull
      - |
        echo "Enter to be created (remote) branch:"
        read BRANCH_NAME;
        git checkout -b ${BRANCH_NAME}
        git push origin ${BRANCH_NAME}
      - git branch
      - git branch --set-upstream-to=origin/main ${BRANCH_NAME}
      - |
        echo "Enter to be created tag: ({{ .TAG_VERSION }}-${BRANCH_NAME})"
        read BRANCH_TAG;
        git tag -a ${BRANCH_TAG} -m 'updated for stuttgart-things {{ .DATE }} for tag version ${BRANCH_TAG}'
        git push --tags

  delete-branch:
    desc: Delete branch from origin
    cmds:
      - git checkout main
      - git branch
      - git pull
      - |
        echo "Enter to be deleted (remote) branch:"
        read BRANCH_NAME;
        git branch -d ${BRANCH_NAME}
        git push origin -d ${BRANCH_NAME}

  lint:
    desc: Lint code
    cmds:
      - cmd: golangci-lint run
        ignore_error: true

  test:
    desc: Test code
    cmds:
      - go mod tidy
      - go test -v

  crds:
    desc: Generate crds
    deps: [lint, test]
    cmds:
      - '{{ .CONTROLLER_GEN_CMD }} rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases'
      - '{{ .CONTROLLER_GEN_CMD }} rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=helm/{{ .PROJECT_NAME }}/crds'

  tag:
    desc: commit, push & tag the module
    deps: [lint]
    cmds:
      - task: git-push
      - go mod tidy
      - git fetch --tags --force
      - git pull --tags
      - git tag -a {{ .UPDATED_TAG_VERSION }} -m 'updated for stuttgart-things {{ .DATE }} for tag version {{ .UPDATED_TAG_VERSION }}'
      - git push origin --tags -f

  build-image:
    desc: Build image
    deps: [tag, crds]
    cmds:
      - "{{ .CONTAINER_RUNTIME_CMD }} build -t {{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .TAG_VERSION }} ."
      - "{{ .CONTAINER_RUNTIME_CMD }} push {{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .TAG_VERSION }}"
      - cd config/manager && {{ .KUSTOMIZE_CMD }} edit set image controller={{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .TAG_VERSION }}

  deploy-crds:
    desc: Generate and deploy crds
    deps: [crds]
    cmds:
      - '{{ .KUSTOMIZE_CMD }} build config/crd > /tmp/{{ .PROJECT_NAME }}-crds.yaml'
      - kubectl get nodes
      - sleep 5
      - kubectl apply -f /tmp/{{ .PROJECT_NAME }}-crds.yaml
      - kubectl get crds

  deploy:
    desc: Build image & deploy
    deps: [deploy-crds, build-image]
    cmds:
      - '{{ .KUSTOMIZE_CMD }} build config/default > /tmp/{{ .PROJECT_NAME }}-deployment.yaml'
      - kubectl get nodes
      - sleep 5
      - envsubst < config/addons/secret.yaml | kubectl apply -f -
      - kubectl apply -f config/addons/template.yaml
      - kubectl apply -f /tmp/{{ .PROJECT_NAME }}-deployment.yaml
      - sleep 5
      - kubectl -n shipyard-operator-system logs -f $(kubectl get pods -o name -n shipyard-operator-system)
    env:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_NAMESPACE: ${VAULT_NAMESPACE}
      VAULT_ADDR: ${VAULT_ADDR}

  push:
    desc: Push to registry
    cmds:
      - task: build-image
      - task: package
      - helm push {{ .PROJECT_NAME }}-{{ .TAG_VERSION }}.tgz oci://{{ .REGISTRY }}/{{ .REPOSITORY_NAME }}
      - rm -rf {{ .PROJECT_NAME }}-{{ .TAG_VERSION }}.tgz
      - task: git-push
    vars:
      PACKAGE:
        sh: "ls *tgz* -Art | tail -n 1"

  package:
    desc: Update Chart.yaml and package archive
    cmds:
      - git add ./helm/*/*
      - yq e -i '.version = "{{ .TAG_VERSION }}"' ./helm/*/Chart.yaml
      - "sed -i 's/appVersion: .*/appVersion: {{ .TAG_VERSION }} /g' ./helm/*/Chart.yaml"
      - yq e -i '.deployment.containers.manager.image = "{{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}"' ./helm/*/values.yaml
      - yq e -i '.deployment.containers.manager.tag = "{{ .DATE }}-{{ .TAG_VERSION }}"' ./helm/*/values.yaml
      - yq e -i '.releases[0].version = "{{ .TAG_VERSION }}"' ./helmfile.yaml
      - helm package ./helm/*/

  git-push:
    desc: Commit & push the module
    cmds:
      - go mod tidy
      - git pull
      - git config advice.addIgnoredFile false
      - git add *
      - git commit -am 'updated {{ .PROJECT_NAME }} {{ .DATE }} for tag version {{ .TAG_VERSION }}{{ .BRANCH }}'
      - git push origin {{ .BRANCH }}

  # INIT TASK
  install-kustomize:
    desc: Download and install-kustomize
    cmds:
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
      - sudo mv kustomize /usr/bin/kustomize
      - sudo chmod +x /usr/bin/kustomize

  merge:
    desc: Create pull request into main
    cmds:
      # - task: git-push
      # - gh pr create -t "merge from {{ .BRANCH }} into main" -b "created pr for {{ .BRANCH }} branch into main"
      # - git switch main
      - gh pr merge $(gh pr list | grep "^[^#;]" | awk '{print $1}') --auto --rebase --delete-branch
      - git branch -D {{ .BRANCH }}