---
version: "3"

vars:
  REGISTRY: eu.gcr.io
  REPOSITORY_NAME: stuttgart-things
  MODULE: github.com/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}
  CONTAINER_RUNTIME_CMD: sudo nerdctl
  CONTROLLER_GEN_CMD: "./bin/controller-gen"
  KUSTOMIZE_CMD: kustomize
  PROJECT_NAME:
    sh: pwd | grep -o "[^/]*$"
  MAJOR:
    sh: git describe --tags --abbrev=0 | cut -d "." -f1
  MINOR:
    sh: git describe --tags --abbrev=0 | cut -d "." -f2
  PATCH:
    sh: git describe --tags --abbrev=0 | cut -d "." -f3
  VERSION:
    sh: git describe --tags --abbrev=0
  DATE:
    sh: date +"%y.%m%d.%H%M"
  UPDATED_TAG:
    sh: old_tag=$(git describe --tags --abbrev=0 | cut -d "." -f3); new_tag=$((old_tag+1)); echo $new_tag
  UPDATED_TAG_VERSION:
    sh: t1=$(git describe --tags --abbrev=0 | cut -f1 -d'.'); t2=$(git describe --tags --abbrev=0 | cut -f2 -d'.'); echo $t1.$t2.{{.UPDATED_TAG}}

tasks:

  install-kustomize:
    desc: Download + install-kustomize
    cmds:
      - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash

  lint:
    desc: Lint code
    cmds:
      - cmd: golangci-lint run
        ignore_error: true
  test:
    desc: Test code
    cmds:
      - go mod tidy
      - go test -v
  crds:
    desc: Generate crds
    deps: [lint, test]
    cmds:
      - '{{ .CONTROLLER_GEN_CMD }} rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases'

  tag:
    desc: commit, push & tag the module
    deps: [lint]
    cmds:
      - go mod tidy
      - git pull
      - git add *
      - git commit -am 'updated {{ .PROJECT_NAME }} {{ .DATE }} for tag version {{ .UPDATED_TAG_VERSION }}'
      - git push
      - git tag -a {{ .UPDATED_TAG_VERSION }} -m 'updated for stuttgart-things {{ .DATE }} for tag version {{ .UPDATED_TAG_VERSION }}'
      - git push origin --tags

  build-image:
    desc: Build image
    deps: [tag, crds]
    cmds:
      - "{{ .CONTAINER_RUNTIME_CMD }} build -t {{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .UPDATED_TAG_VERSION }} ."
      - "{{ .CONTAINER_RUNTIME_CMD }} push {{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .UPDATED_TAG_VERSION }}"
      - cd config/manager && {{ .KUSTOMIZE_CMD }} edit set image controller={{ .REGISTRY }}/{{ .REPOSITORY_NAME }}/{{ .PROJECT_NAME }}:{{ .DATE }}-{{ .UPDATED_TAG_VERSION }}

  deploy-crds:
    desc: Generate and deploy crds
    deps: [crds]
    cmds:
      - '{{ .KUSTOMIZE_CMD }} build config/crd > /tmp/{{ .PROJECT_NAME }}-crds.yaml'
      - kubectl get nodes
      - sleep 5
      - kubectl apply -f /tmp/{{ .PROJECT_NAME }}-crds.yaml
      - kubectl get crds

  deploy:
    desc: Build image & deploy
    deps: [deploy-crds, build-image]
    cmds:
      - '{{ .KUSTOMIZE_CMD }} build config/default > /tmp/{{ .PROJECT_NAME }}-deployment.yaml'
      - kubectl get nodes
      - sleep 5
      - envsubst < config/addons/secret.yaml | kubectl apply -f -
      - kubectl apply -f config/addons/template.yaml
      - kubectl apply -f /tmp/{{ .PROJECT_NAME }}-deployment.yaml
      - sleep 5
      - kubectl -n shipyard-operator-system logs -f $(kubectl get pods -o name -n shipyard-operator-system)
    env:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_NAMESPACE: ${VAULT_NAMESPACE}
      VAULT_ADDR: ${VAULT_ADDR}

  package:
    desc: Update Chart.yaml and package archive
    cmds:
      - git add ./helm/*/*
      - yq e -i '.version = "{{ .UPDATED_TAG_VERSION }}"' ./helm/*/Chart.yaml
      - "sed -i 's/appVersion: .*/appVersion: {{ .UPDATED_TAG_VERSION }}/g' ./helm/*/Chart.yaml"
      - yq e -i '.deployment.containers.manager.tag = "{{ .DATE }}-{{ .UPDATED_TAG_VERSION }}"' ./helm/*/values.yaml
      - helm package ./helm/*/

  push:
    desc: Push to registry
    deps: [build-image, package]
    cmds:
      - helm push {{ .PROJECT_NAME }}-{{ .UPDATED_TAG_VERSION }}.tgz oci://{{ .REGISTRY }}/{{ .REPOSITORY_NAME }}
      - rm -rf {{ .PROJECT_NAME }}-{{ .UPDATED_TAG_VERSION }}.tgz
    vars:
      PACKAGE:
        sh: "ls *tgz* -Art | tail -n 1"
