# permissions for end users to edit ansibles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansible-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: machine-shop-operator
    app.kubernetes.io/part-of: machine-shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansible-editor-role
rules:
- apiGroups:
  - machineshop.sthings.tiab.ssc.sva.de
  resources:
  - ansibles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machineshop.sthings.tiab.ssc.sva.de
  resources:
  - ansibles/status
  verbs:
  - get
