apiVersion: v2
name: machine-shop-operator
description: A Helm chart for Kubernetes
type: application
version: '0.1.11'
appVersion: 0.1.11 
dependencies:
  - name: sthings-helm-toolkit
    version: 2.4.42
    repository: oci://eu.gcr.io/stuttgart-things
