apiVersion: v2
name: machine-shop-operator
description: A Helm chart for Kubernetes
type: application
version: 'v0.1.63'
appVersion: v0.1.63 
dependencies:
  - name: sthings-helm-toolkit
    version: 2.4.42
    repository: oci://eu.gcr.io/stuttgart-things
  - name: redis
    version: 17.11.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
