---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machine-shop-operator-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev8
    namespace: machine-shop-operator-system
    #server: 'https://10.100.136.78:6443'
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: machine-shop-operator
    targetRevision: v0.1.48
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            secrets:
              vault:
                name: vault
                namespace: machine-shop-operator-system
                secretKVs:
                  VAULT_ADDR: <path:apps/data/vault#addr>
                  VAULT_ROLE_ID: <path:apps/data/vault#roleID>
                  VAULT_SECRET_ID: <path:apps/data/vault#secretID>
                  VAULT_NAMESPACE: <path:apps/data/vault#namespace>
            configmaps:
              environment:
                ENABLE_WEBHOOK: "yes"
                WEBHOOK_URL: "https://365sva.webhook.office.com/webhookb2/2f14a9f8-4736-46dd-9c8c-31547ec37180@0a65cb1e-37d5-41ff-980a-647d9d0e4f0b/IncomingWebhook/a993544595464ce6af4f2f0461d55a17/dc3a27ed-396c-40b7-a9b2-f1a2b6b44efe"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
