apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machine-shop-operator-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev8
    namespace: machine-shop-operator-system
    #server: 'https://10.100.136.78:6443'
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: machine-shop-operator
    targetRevision: v0.1.39
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            secrets:
              vault:
                name: vault
                namespace: machine-shop-operator-system
                secretKVs:
                  VAULT_ADDR: <path:apps/data/vault#addr>
                  VAULT_ROLE_ID: <path:apps/data/vault#roleID>
                  VAULT_SECRET_ID: <path:apps/data/vault#secretID>
                  VAULT_NAMESPACE: <path:apps/data/vault#namespace>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
