apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machine-shop-operator-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev11
    namespace: machine-shop-operator-system
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: machine-shop-operator
    targetRevision: v0.1.59
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            redis:
              auth:
                password: <path:apps/data/machine-shop-operator#redisPassword>
            secrets:
              redis:
                name: redis
                namespace: machine-shop-operator-system
                secretKVs:
                  REDIS_PASSWORD: <path:apps/data/machine-shop-operator#redisPassword>
              vault:
                name: vault
                namespace: machine-shop-operator-system
                secretKVs:
                  VAULT_ADDR: <path:apps/data/vault#addr>
                  VAULT_ROLE_ID: <path:apps/data/vault#roleID>
                  VAULT_SECRET_ID: <path:apps/data/vault#secretID>
                  VAULT_NAMESPACE: <path:apps/data/vault#namespace>
            configmaps:
              redis-connection:
                REDIS_SERVER: "machine-shop-operator-deployment-redis-headless.machine-shop-operator-system.svc.cluster.local"
                REDIS_PORT: "6379"
              environment:
                ENABLE_WEBHOOK: "yes"
                WEBHOOK_URL: "https://365sva.webhook.office.com/webhookb2/2f14a9f8-4736-46dd-9c8c-31547ec37180@0a65cb1e-37d5-41ff-980a-647d9d0e4f0b/IncomingWebhook/a993544595464ce6af4f2f0461d55a17/dc3a27ed-396c-40b7-a9b2-f1a2b6b44efe"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
