---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tkn-machine-shop-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: app
  destination:
    name: dev11
    namespace: tekton-cd
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: yacht-tekton-resources
    targetRevision: v0.47.10
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            enableRuns: true
            runs:
              buildKanikoImage:
                name: build-mso-kaniko-3
                addRandomDateToRunName: false
                namespace: tekton-cd
                kind: Pipeline
                ref: build-kaniko-image
                params:
                  gitRepoUrl: git@github.com:stuttgart-things/machine-shop-operator.git
                  git-revision: main
                  context: /kaniko/mso
                  gitWorkspaceSubdirectory: /kaniko/mso
                  image: scr.app.4sthings.tiab.ssc.sva.de/machine-shop-operator/mso
                  tag: 0.8.15
                  registry: eu.gcr.io
                  dockerfile: Dockerfile
                workspaces:
                  ssh-credentials:
                    workspaceKind: secret
                    workspaceRef: github-ssh
                  shared-workspace:
                    workspaceKind: persistentVolumeClaim
                    workspaceRef: kaniko-workspace
                  dockerconfig:
                    workspaceKind: secret
                    workspaceRef: scr-labda-vsphere
              # buildHelmGithub:
              #   name: build-mso-helm-3
              #   addRandomDateToRunName: false
              #   namespace: tekton-cd
              #   kind: Pipeline
              #   ref: package-publish-helmchart
              #   params:
              #     git-repo-url: git@github.com:stuttgart-things/machine-shop-operator.git
              #     git-revision: main
              #     gitWorkspaceSubdirectory: /helm/mso
              #     helm-chart-name: machine-shop-operator
              #     helm-chart-tag: 0.8.15
              #     registry: scr.app.4sthings.tiab.ssc.sva.de
              #     working-image: "eu.gcr.io/stuttgart-things/sthings-k8s:1.127.2"
              #   workspaces:
              #     ssh-credentials:
              #       workspaceKind: secret
              #       workspaceRef: github-ssh
              #     shared-workspace:
              #       workspaceKind: persistentVolumeClaim
              #       workspaceRef: helm-workspace
              #     dockerconfig:
              #       workspaceKind: secret
              #       workspaceRef: scr-labda-vsphere
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
