# Source: yacht-tekton-resources/templates/runs.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: helm-mso0-5-02
  namespace: tekton-cd
spec:
  pipelineRef:
    name: package-publish-helmchart
  workspaces:
    - name: dockerconfig
      secret:
        secretName: scr-labda-vsphere
    - name: source
      persistentVolumeClaim:
        claimName: helm-workspace
    - name: ssh-credentials
      secret:
        secretName: github-ssh
  params:
    - name: git-repo-url
      value: "git@github.com:stuttgart-things/machine-shop-operator.git"
    - name: git-revision
      value: "main"
    - name: gitWorkspaceSubdirectory
      value: "/helm/mso"
    - name: helm-chart-name
      value: "machine-shop-operator"
    - name: helm-chart-path
      value: "helm"
    - name: helm-chart-tag
      value: "v1.4.9"
    - name: registry
      value: "scr.app.4sthings.tiab.ssc.sva.de"
    - name: working-image
      value: "eu.gcr.io/stuttgart-things/sthings-k8s:1.127.2"
