{{ if not .Values.tektonResources.enabled }}
{{- $envVar := . -}}
{{- range $configmapName, $configmapTpl := .Values.configmaps -}}
{{ include "sthings-helm-toolkit.configmap" (list $envVar $configmapName $configmapTpl) }}
{{ end -}}
{{ end -}}